# Generated by Django 5.2 on 2025-05-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureApp', '0004_remove_contactus_date_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetInTouchFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(choices=[('+1', '🇺🇸 +1 (USA)'), ('+44', '🇬🇧 +44 (UK)'), ('+234', '🇳🇬 +234 (Nigeria)'), ('+91', '🇮🇳 +91 (India)')], max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('Partnership', 'Partnership'), ('General Enquiries', 'General Enquiries'), ('Energy Solutions Enquiries', 'Energy Solutions Enquiries')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyAbroadFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(choices=[('+1', '🇺🇸 +1 (USA)'), ('+44', '🇬🇧 +44 (UK)'), ('+234', '🇳🇬 +234 (Nigeria)'), ('+91', '🇮🇳 +91 (India)')], max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('uploaded_file', models.FileField(upload_to='study_abroad_uploads/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
