# Generated by Django 5.2 on 2025-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureApp', '0006_store_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyabroadformsubmission',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='studyabroadformsubmission',
            name='course_of_interest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyabroadformsubmission',
            name='level_of_study_of_interest',
            field=models.CharField(blank=True, choices=[('Diploma', 'Diploma'), ('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
    ]
