# Generated by Django 5.2 on 2025-06-03 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureApp', '0007_remove_studyabroadformsubmission_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyabroadformsubmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='studyabroadformsubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='study_abroad_uploads/'),
        ),
    ]
