# Generated by Django 5.2 on 2025-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FutureApp', '0008_studyabroadformsubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getintouchformsubmission',
            name='country_code',
            field=models.CharField(choices=[('+1', '+1 (USA)'), ('+44', '+44 (UK)'), ('+234', '+234 (Nigeria)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)'), ('+61', '+61 (Australia)'), ('+27', '+27 (South Africa)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+31', '+31 (Netherlands)'), ('+46', '+46 (Sweden)'), ('+47', '+47 (Norway)'), ('+41', '+41 (Switzerland)')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studyabroadformsubmission',
            name='country_code',
            field=models.CharField(choices=[('+1', '+1 (USA)'), ('+44', '+44 (UK)'), ('+234', '+234 (Nigeria)'), ('+91', '+91 (India)'), ('+86', '+86 (China)'), ('+49', '+49 (Germany)'), ('+33', '+33 (France)'), ('+81', '+81 (Japan)'), ('+61', '+61 (Australia)'), ('+27', '+27 (South Africa)'), ('+55', '+55 (Brazil)'), ('+52', '+52 (Mexico)'), ('+7', '+7 (Russia)'), ('+82', '+82 (South Korea)'), ('+39', '+39 (Italy)'), ('+34', '+34 (Spain)'), ('+31', '+31 (Netherlands)'), ('+46', '+46 (Sweden)'), ('+47', '+47 (Norway)'), ('+41', '+41 (Switzerland)')], max_length=5),
        ),
    ]
